### ISSUE TITLE
Change Color not reflecting - Always red

### ISSUE THREAD

**Issue by greatapps** [tuya/tuya-home-android-sdk#17]
I have a Syska LED which is paring and On if working perfectly but the color is not changing. I have tried everything, Attaching some Screenshots
![WhatsApp Image 2021-01-12 at 1 28 14 PM](https://user-images.githubusercontent.com/7997742/104510607-6b538300-5611-11eb-905d-5887f15b45bf.jpeg)
![WhatsApp Image 2021-01-12 at 1 28 26 PM](https://user-images.githubusercontent.com/7997742/104510613-6c84b000-5611-11eb-92c2-ecb5c1bb4133.jpeg)
![WhatsApp Image 2021-01-12 at 1 28 46 PM](https://user-images.githubusercontent.com/7997742/104510619-6db5dd00-5611-11eb-9c38-014c457bd7cf.jpeg)
![WhatsApp Image 2021-01-12 at 1 29 37 PM](https://user-images.githubusercontent.com/7997742/104510622-6db5dd00-5611-11eb-8b9b-1ca7fdc0a25f.jpeg)

**Comment by xiaoxuan-Tuya** [comment]
Hi , @greatapps 

> working perfectly but the color is not changing

Does it work when setting other function points like the  luminance ?  You need to confirm the  definition of the your  product function points . In your case ,  make sure that `24` is the `dpId` of the color function (you could check the `dps` of **DeviceBean** data model) . If it still doesn't work , please post the error message from service and we will check it .
