### ISSUE TITLE
3.22 - arm64-v8a 版本 .so文件

### ISSUE THREAD

**Issue by ucssi-dongxd** [tuya/tuya-home-android-sdk#21]
哪里可以下载arm64-v8a版本的 3.22版本的so资源文件呢？

**Comment by Innocencellh** [comment]
3.10.0 版本之前的 SDK 只支持安卓 armeabi-v7a。3.11.0 版本后已经将 armeabi-v7a、arm64-v8a 集成进 SDK。您需要将本地自行放入的 SDK 的相关 so 库移除，使用 SDK 中提供的。
