### ISSUE TITLE
Bug: QRCode Image Color Inverted on Dark theme (when it is enabled)

### ISSUE THREAD

**Issue by tanshuai** [tuya/tuya-home-android-sdk#22]
Use the [latest code](https://github.com/tuya/tuya-home-android-sdk/commit/2902aaf64df8e428996ae2da5188cde71afa6f12) of this project and enable Android Dark theme feature.

QRCode Image Color will be Inverted when Dark them is enabled by Android System.  This bug also occurs in newer versions such as ```com.tuya.smart:tuyasmart:3.27.7```.

**Incorrect QRCode with Inverted Color when Dark theme is enabled**
![Incorrect QRCode with Inverted Color when Dark theme is enabled](https://user-images.githubusercontent.com/3947852/125933512-0938dcf3-f28a-44ab-a0c5-033f6bfc10c3.png)

**Correct QRCode**
![Correct QRCode](https://user-images.githubusercontent.com/3947852/125933434-f8393f6c-07d2-4dc6-83ec-15313a59c7ac.png)

**Comment by TuyaRockSugar** [comment]
emm,t he QR code is OK. Check whether the location permission is turned on. The scanning result is that ssid is not obtained

**Comment by tanshuai** [comment]
@TuyaRockSugar 

Thank you for your reply.

> emm,t he QR code is OK. 

The QR Code (Inverted Color)  cannot be recognized by [TUYA_IPC_SDK](https://github.com/TuyaInc/TUYA_IPC_SDK) / 
[tuya-iotos-embeded-sdk-multimedia](https://github.com/tuya/tuya-iotos-embeded-sdk-multimedia)   (the IPC SDK for embedded device).

> Check whether the location permission is turned on. 

Not relevant to this issue.

>The scanning result is that ssid is not obtained

As you saw the ssid is <unknown ssid>, I think you scan the incorrect QR Code (Inverted Color) with WeChat. 

Please note: 
1. the most Apps such as WeChat can be successfully scanned the incorrect QR Code (Inverted Color), because these apps support Inverted Color QR Code.
2. But, the TUYA_IPC_SDK  can't scan the incorrect QR Code (Inverted Color).


Pls try use a real device camera to scan the incorrect QR Code (Inverted Color).

**Comment by tanshuai** [comment]
![fix-qr-code-bug](https://user-images.githubusercontent.com/3947852/130221621-70f49c23-a3d0-499f-8021-9b6d0836d28b.jpeg)

This problem has been fixed by a workaround. 

Please consider the official fix as it is  very simple with few lines of code.
